### ISSUE TITLE
[Duovero] USB OTG does not work as host

### ISSUE THREAD

**Issue by adam-lee** [gumstix/yocto-manifest#31]
Message `musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active` indefinitely prints

```
root@duovero:~$  modprobe g_serial
 gadget: Gadget Serial v2.4
 gadget: g_serial ready
musb-hdrc musb-hdrc: MUSB HDRC host driver
musb-hdrc musb-hdrc: new USB bus registered, assigned bus number 3
usb usb3: New USB device found, idVendor=1d6b, idProduct=0002
usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
usb usb3: Product: MUSB HDRC host driver
usb usb3: Manufacturer: Linux 3.6.11-yocto-standard musb-hcd
usb usb3: SerialNumber: musb-hdrc
hub 3-0:1.0: USB hub found
hub 3-0:1.0: 1 port detected
root@duovero:~$  usb 3-1: new high-speed USB device number 2 using musb-hdrc
usb 3-1: New USB device found, idVendor=0409, idProduct=005a
usb 3-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
hub 3-1:1.0: USB hub found
hub 3-1:1.0: 4 ports detected
usb 3-1: USB disconnect, device number 2
usb 3-1: new high-speed USB device number 3 using musb-hdrc
usb 3-1: New USB device found, idVendor=0409, idProduct=005a
usb 3-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
hub 3-1:1.0: USB hub found
hub 3-1:1.0: 4 ports detected
musb_stage0_irq 486: bogus host RESUME (a_wait_bcon)
musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active
^C
root@duovero:~$  musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active
musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active
musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active
musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active
musb_bus_suspend 2308: trying to suspend as a_wait_bcon while active
```

**Comment by darebear** [comment]
Hello,
I've been trying to get the USB-OTG port on my Overo to talk to my webcam for a while now and I have not been able to make this happen thus far. One of your builds is allowing me to connect to a keyboard and mouse through the USB Host port of the Tobi board (with or without powered hub). 

I can connect to the keyboard or mouse via the USB-OTG port, however, they seem to be USB low-speed devices. If I connect a device that is labeled as "high-speed" then I start having issues with devices rejection enumeration regardless of whether I use a powered USB hub or not. 

Example message:

``
[   98.010406] usb 2-1: new high-speed USB device number 2 using musb-hdrc
``
``   
[   98.135406] usb 2-1: device descriptor read/64, error -71   
``
``
[   98.369781] usb 2-1: device descriptor read/64, error -71   
``
``
[   98.604156] usb 2-1: new high-speed USB device number 3 using musb-hdrc
``
``
[   98.729125] usb 2-1: device descriptor read/64, error -71
``
``
[   98.963531] usb 2-1: device descriptor read/64, error -71
``
``
[   99.197906] usb 2-1: new high-speed USB device number 4 using musb-hdrc
``
``
[   99.619750] usb 2-1: device not accepting address 4, error -71
``
``
[   99.744781] usb 2-1: new high-speed USB device number 5 using musb-hdrc
``
``
[  100.166625] usb 2-1: device not accepting address 5, error -71
``
``
[  100.172882] hub 2-0:1.0: unable to enumerate USB device on port 1
``
``
[  102.182342] musb_bus_suspend 2304: trying to suspend as a_host while active
``
``
[  102.315093] usb 2-1: new high-speed USB device number 6 using musb-hdrc
``
``
[  102.440246] usb 2-1: device descriptor read/64, error -71
``
``
[  102.674468] usb 2-1: device descriptor read/64, error -71
``
``
[  102.908874] usb 2-1: new high-speed USB device number 7 using musb-hdrc
``
``
[  103.033966] usb 2-1: device descriptor read/64, error -71
``

Other things to note: 
- I read your [one-pager](https://github.com/gumstix/yocto-manifest/wiki/One-Pager-on-Gumstix-Yocto-Project-1.7).   
- Since the peripherals I want to connect to require more than the 100mA provided by the Gumstix, I've followed [Dugas's](http://blogdugas.net/blog/2015/05/12/use-a-device-with-the-usb-otg-port-of-a-gumstix/) instructions. 
- I've built from Yocto, used Live-Build, and Ubuntu. 

Questions:
- Is there any build that you know of that has a properly and fully working USB-OTG port?
