### ISSUE TITLE
wks files not exist

### ISSUE THREAD

**Issue by will2km** [gumstix/yocto-manifest#67]
Image has been built, but after running
`wic create sdimage-gumstix -e gumstix-console-image`

I go the following message
`Checking basic build environment...`
`Done.`
`Creating image(s)...`
`No image named sdimage-gumstix found, exiting.  (Use 'wic list images' to list available images, or specify a fully-qualified OE kickstart (.wks) filename)`

And there is no kickstart file in the directory described in the build manual
`meta-gumstix-extras/scripts/lib/image/canned-wks/`

**Comment by texierp** [comment]
Hi @will2km, 

The problem comes from the new path (see http://lists.openembedded.org/pipermail/openembedded-core/2015-September/109833.html).

If you rename 'scripts/lib/image/canned-wks/' to 'scripts/lib/wic/canned-wks/', normally it works.

After that you can enter the following cdmline : 

 `wic list images`

and see

`sdimage-gumstix     Create SD card image with a boot partition`

I think the best way is to generate a patch.

Pierre-Jean

**Comment by yangjiel** [comment]
Close for no feedback. If you have further question regarding this, please reopen it.
